#!/usr/bin/env python3
"""Generate the public student topic data from the curated basket.

Design principle (no research secrets leak):
- The *only* student-facing content comes from tools/basket.json, which is
  hand-curated and anonymised.
- forschungsideen.json is used ONLY to (a) verify provenance of each topic's
  `source` id and (b) run a leakage check that no raw collaborator names,
  internal notes, links or idea ids appear in the published output.

Outputs:
- data/topics.js      -> window.TOPICS  (consumed offline & on GitHub Pages)
- thesis_topics.md    -> human-readable, bilingual topic list

Usage:  python3 tools/build_topics.py
Zero third-party dependencies (standard library only).
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASKET = ROOT / "tools" / "basket.json"
DATA_OUT = ROOT / "data" / "topics.js"
MD_OUT = ROOT / "thesis_topics.md"

# The private research database lives outside this repo (Cowork environment).
# Override with --db <path> if it moved.
DEFAULT_DB = ROOT.parent / "MCP_Claude_Forschung" / "Research N" / "forschungsideen.json"


def load_db(db_path: Path):
    if not db_path.exists():
        print(f"WARN: research DB not found at {db_path} — provenance & leak checks skipped.")
        return None
    return json.loads(db_path.read_text(encoding="utf-8"))


def collect_secret_strings(db) -> set[str]:
    """Raw strings that must never appear in published output."""
    secrets: set[str] = set()
    for idea in db.get("ideen", []):
        secrets.add(idea.get("id", ""))
        for kol in idea.get("kollaboratoren", []) or []:
            if isinstance(kol, str) and len(kol) > 2:
                secrets.add(kol)
        note = idea.get("notizen")
        if isinstance(note, str) and len(note) > 8:
            secrets.add(note)
        for link in idea.get("links", []) or []:
            if isinstance(link, str) and len(link) > 4:
                secrets.add(link)
    return {s for s in secrets if s}


def topic_text_blob(topic) -> str:
    parts = []
    for lang in ("de", "en"):
        d = topic.get(lang, {})
        parts += [d.get("title", ""), d.get("summary", ""), d.get("scope", "")]
        parts.append(topic.get("data", {}).get(lang, ""))
    parts += topic.get("tags", [])
    return "\n".join(parts)


def main(argv):
    db_path = DEFAULT_DB
    if "--db" in argv:
        db_path = Path(argv[argv.index("--db") + 1]).expanduser()

    basket = json.loads(BASKET.read_text(encoding="utf-8"))
    lines = basket["research_lines"]
    line_ids = {l["id"] for l in lines}
    topics = basket["topics"]
    db = load_db(db_path)

    errors: list[str] = []
    warnings: list[str] = []

    # Validate line references
    for t in topics:
        if t["line"] not in line_ids:
            errors.append(f"Topic source={t.get('source')} references unknown line '{t['line']}'")
        for lang in ("de", "en"):
            if not t.get(lang, {}).get("title"):
                errors.append(f"Topic source={t.get('source')} missing {lang}.title")

    # Provenance + leakage checks against the private DB
    if db is not None:
        valid_ids = {i.get("id") for i in db.get("ideen", [])}
        secrets = collect_secret_strings(db)
        for t in topics:
            src = t.get("source")
            if src and src not in valid_ids:
                warnings.append(f"source '{src}' not found in research DB (provenance unverified)")
            blob = topic_text_blob(t)
            for s in secrets:
                if s and s in blob:
                    errors.append(f"LEAK: secret string '{s[:40]}...' appears in topic source={src}")

    if errors:
        print("BUILD FAILED:")
        for e in errors:
            print("  ✗", e)
        return 1
    for w in warnings:
        print("  !", w)

    # ---- Emit data/topics.js (strip `source` — provenance stays private) ----
    public_topics = []
    for t in topics:
        public_topics.append({
            "line": t["line"],
            "level": t.get("level", []),
            "tags": t.get("tags", []),
            "data": t.get("data", {}),
            "de": t["de"],
            "en": t["en"],
        })
    payload = {"lines": lines, "topics": public_topics, "count": len(public_topics)}
    DATA_OUT.parent.mkdir(parents=True, exist_ok=True)
    DATA_OUT.write_text(
        "// AUTO-GENERATED by tools/build_topics.py — do not edit by hand.\n"
        "// Source of truth: tools/basket.json (curated, anonymised).\n"
        "window.TOPICS = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )

    # ---- Emit human-readable bilingual markdown ----
    by_line = {l["id"]: [] for l in lines}
    for t in topics:
        by_line[t["line"]].append(t)
    md = ["# Offene Themen für Abschlussarbeiten / Open thesis topics", "",
          "> Automatisch erzeugt aus `tools/basket.json`. Bearbeitung dort, dann `python3 tools/build_topics.py`.",
          "> Auto-generated from `tools/basket.json`. Edit there, then re-run the generator.",
          "",
          "Die Themen sind kuratiert, anonymisiert und nach **Forschungslinien** gruppiert — "
          "jede Linie zahlt auf ein größeres Forschungsprinzip ein.",
          "Topics are curated, anonymised and grouped by **research line**.",
          ""]
    for l in lines:
        md.append(f"## {l['de']} — {l['en']}")
        md.append("")
        for t in by_line[l["id"]]:
            de, en = t["de"], t["en"]
            level = ", ".join(t.get("level", []))
            md.append(f"### {de['title']} — *{en['title']}*")
            md.append(f"*{level}* · {', '.join('`'+x+'`' for x in t.get('tags', []))}")
            md.append("")
            md.append(de["summary"])
            md.append("")
            data_de = t.get("data", {}).get("de")
            if data_de:
                md.append(f"**Datenbasis:** {data_de}")
                md.append("")
            md.append(f"**Möglicher Zuschnitt:** {de['scope']}")
            md.append("")
    MD_OUT.write_text("\n".join(md), encoding="utf-8")

    print(f"OK: wrote {DATA_OUT.relative_to(ROOT)} and {MD_OUT.relative_to(ROOT)} "
          f"({len(public_topics)} topics, {len(lines)} lines).")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
